### ISSUE TITLE
MalformedByteSequenceException：Windows下xml中的汉字导致编译不过

### ISSUE THREAD

**Issue by pisfans** [fashare2015/MVVM-JueJin#1]
Error:com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 3 字节的 UTF-8 序列的字节 3 无效。
Error:java.lang.RuntimeException: failure, see logs for details.
Error:com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 3 字节的 UTF-8 序列的字节 3 无效。
Error:Execution failed for task ':app:kaptDebugKotlin'.
> Internal compiler error. See log for more details

**Comment by fashare2015** [comment]
不知道你的os是mac还是windows.搜了一下，这个问题可能是汉字编码导致的，请确保ide是utf-8编码 。

**Comment by pisfans** [comment]
gradle还是2.14，不打算升到3.4.1吗？,你这个项目打不打算适配到as3.0呢?

**Comment by pisfans** [comment]
我的是windows,

**Comment by fashare2015** [comment]
最近没时间升级ide，3.0也就内置了kotlin支持吧？AS2.x配合kotlin插件，和3.0应该没啥区别

**Comment by fashare2015** [comment]
@pisfans [Android 关于DataBinding在Windows上中文字符的bug](http://blog.csdn.net/johnny901114/article/details/54915546)
问题已解决，两种方案：
1. 全员配备mac.(滑稽)
2. 用windows的话，规范一点，xml 中的所有汉字提取成string资源 `@string/xxx`

**Comment by DravenForProgram** [comment]
我的android studio 是3.0版本，在模拟机运行时报错
Error:Execution failed for task ':databinding:kaptDebugKotlin'.
> Internal compiler error. See log for more details
我是window平台的，我是小白啊，但是感觉是不是3.0版本才会有这样的问题

**Comment by fashare2015** [comment]
@DravenForProgram 你在根目录下build.gradle里，把kapt相关的注释掉试一下：
- apply plugin: 'kotlin-kapt'
- kapt "com.android.databinding:compiler:$rootProject.ext.android_plugin_version"

不行的话，我装一个AS3.0看一下

**Comment by DravenForProgram** [comment]
Error:Cause: compileSdkVersion is not specified. 注释掉了以后是这样子的

**Comment by fashare2015** [comment]
@DravenForProgram 我昨天装了AS3.0是可以run起来的(没有注释掉任何东西)。
![image](https://user-images.githubusercontent.com/15076541/30945805-e237242a-a432-11e7-9a9f-26f811cdece0.png)
你再run一下，看下`gradle console`的具体错误原因。
![image](https://user-images.githubusercontent.com/15076541/30945897-60157234-a433-11e7-9cba-9e040ac656df.png)

**Comment by DravenForProgram** [comment]
我去掉注释运行时这个样子的 
gradle console
![qq 20170929141222](https://user-images.githubusercontent.com/21258551/31003078-4f8fe514-a520-11e7-9ca7-b39d8753da9b.png)
![qq 20170929141232](https://user-images.githubusercontent.com/21258551/31003079-4f9bccda-a520-11e7-9c94-b955beb150e0.png)

**Comment by fashare2015** [comment]
@DravenForProgram 貌似和Issue #4 是同一个问题，已经解决了，你重新拉一下代码再编译试试
