### ISSUE TITLE
android plugin 3.0 跑不了

### ISSUE THREAD

**Issue by xiaozhang-carl** [fashare2015/MVVM-JueJin#11]

**Comment by fashare2015** [comment]
给点gradle错误日志，gradle版本等信息

**Comment by muziling** [comment]
有没有打算glide版本升级到4
3.0 报的错，kotlin版本是1.1.60
****/ data binding error ****msg:Cannot find the setter for attribute 'bind:listVM' with parameter type com.fashare.mvvm_juejin.viewmodel.ArticleVM on com.fashare.mvvm_juejin.databinding.GTwoWayListBinding.
file:E:\MVVM-JueJin-master\app\src\main\res\layout\activity_article.xml

**Comment by fashare2015** [comment]
@muziling 默认的gradle配置有哪些改动吗？git diff 一下，贴出来，我这边好复现一下问题。

**Comment by muziling** [comment]
git diff附件, diff文件顺序好像弄反了
[as3.zip](https://github.com/fashare2015/MVVM-JueJin/files/1482101/as3.zip)

**Comment by fashare2015** [comment]
看到改动了，我周末给弄一下。你急的话可以先回退到默认配置来run.

**Comment by fashare2015** [comment]
@muziling android plugin 3.0 已支持
