### ISSUE TITLE
关于在VM中保留View引用的问题

### ISSUE THREAD

**Issue by rayworks** [fashare2015/MVVM-JueJin#14]
Hi 留意到VM的部分实现，如```ArticleVM``` 中保存了对view （如```RecyclerView```）的引用。
个人认为如果想要达成更好的复用， ViewModel中可以除去对View的直接引用吧。
不知在当前代码的实现层面是否有别的考虑？

更多对于MVVM的讨论 可以参考[这里](https://stackoverflow.com/questions/5421874/basic-concepts-of-mvvm-what-should-a-viewmodel-do).

**Comment by fashare2015** [comment]
嗯，你看的很细，这里我偷懒了。理论上VM不该持有view。更规范的话，应该像mvp那样，定义接口IView，vm则类似P层，通过操作IView间接控制view层。
