### ISSUE TITLE
运行到手机上出错

### ISSUE THREAD

**Issue by swallowsonny** [fashare2015/MVVM-JueJin#2]
Error:java.lang.RuntimeException: failure, see logs for details.
Error:com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: 3 字节的 UTF-8 序列的字节 3 无效。
Error:Execution failed for task ':app:kaptDebugKotlin'.
> Internal compiler error. See log for more details

**Comment by fashare2015** [comment]
同 #1，windows 上(UTF-8)报错，我找时间看一下。

**Comment by swallowsonny** [comment]
@fashare2015 好得

**Comment by fashare2015** [comment]
@swallowsonny 我这边的开发环境是mac

**Comment by fashare2015** [comment]
@swallowsonny 问题已解决，详见 #1
