### ISSUE TITLE
你好  我这里始终运行不起来

### ISSUE THREAD

**Issue by GGjin** [fashare2015/MVVM-JueJin#8]
![image](https://user-images.githubusercontent.com/19795509/31933507-e9dffe5e-b86e-11e7-87fc-62f3eeb19b3c.png)
[](url)

为了能够打开这个项目 我gradle用的是4.1  as版本是3.0  kotlin版本是1.1.51

**Comment by fashare2015** [comment]
稍等，我换下gradle版本复现一下看看。你那边方便先用原工程配置的版本吗？

**Comment by fashare2015** [comment]
@GGjin 你具体改动了哪些配置？`git diff`贴出来看一下：
![image](https://user-images.githubusercontent.com/15076541/31948706-3a32cc14-b89d-11e7-85cd-10d031eca694.png)

**Comment by GGjin** [comment]
你用的as版本是多少啊  我是用2.3打不开 才用3.0 试试的  2.3 就是一直在build  那我用原配置 打开试试

**Comment by fashare2015** [comment]
和AS版本没关系，打不开是因为下载grade, kotlin 比较慢。你可以先打开，再改回原配置。记得不要点"grade sync"那个按钮，而是命令行输入'./gradlew'来同步，这样可以看下载进度。

**Comment by GGjin** [comment]
我 一直就是第一次打开之前 吧kotlin的版本 改成我现在已经有的51.。。。 我这回除了 kotlin的版本 其他的都没改  前两天貌似是 蓝灯不好使 gralde下载好久 今天还好 下载完了就能跑了  谢谢了  我这一阵在准备 重构手上的项目  用kotlin+mvp  看看你的项目很有帮助

**Comment by fashare2015** [comment]
恩，蓝灯我用着感觉还行。主要是grade本来就大40+M呢
