### ISSUE TITLE
MainActivity 的Menu的item点击无效，小米max

### ISSUE THREAD

**Issue by ghost** [fashare2015/MVVM-JueJin#9]

**Comment by junjundeyuanwang** [comment]
重写onOptionsItemSelected(MenuItem item)或者把点击事件代码移动到onPostCreate(Bundle savedInstanceState)方法中

**Comment by fashare2015** [comment]
？？？你说的是啥，我代码里没有menu啊

**Comment by ghost** [comment]
我才发现过来，搞错了开源项目，对不起，你删除吧或者close

**Comment by fashare2015** [comment]
好的，没事
